# Generated by Django 3.0.2 on 2020-01-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200112_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Białe', 'Białe'), ('Czerwone', 'Czerwone'), ('Różowe', 'Różowe')], default='Czerwone', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='flavor',
            field=models.CharField(choices=[('Wytrawne', 'Wytrawne'), ('Półwytrawne', 'Półwytrawne'), ('Słodkie', 'Słodkie'), ('Półsłodkie', 'Półsłodkie')], default='Wytrawne', max_length=20),
            preserve_default=False,
        ),
    ]
