# Generated by Django 3.0.2 on 2020-01-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200112_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('Argentyna', 'Argentyna'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Francja', 'Francja'), ('Włochy', 'Włochy'), ('Portugalia', 'Portugalia'), ('Gruzja', 'Gruzja'), ('Mołdawia', 'Mołdawia')], max_length=10),
        ),
    ]
