# Generated by Django 3.0.2 on 2020-01-19 17:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20200119_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specimen',
            name='date_ordered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Product'),
        ),
    ]
