# Generated by Django 3.0.2 on 2020-01-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_remove_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
    ]
